 version: '2'
 services:
   db:
     container_name: 'mysql-blog'
     image: 'mysql'
     ports:
      - '3306:3306'
     environment:
      - MYSQL_ROOT_PASSWORD= '12345'
      - MYSQL_DATABASE= 'blog'
      - MYSQL_USER= 'root'
     volumes:
      - ./mysql:/var/lib/mysql
   web:
     container_name: wordpress-blog
     image: wordpress:4.7.5-apache
     volumes:
       - ./code:/var/www/html
     ports:
       - '8080:80'
     links:
       - 'db:mysql'
     depends_on:
       - db